fixtures:
  forge_modules:
    epel: 'stahnma-epel'
  repositories:
    stdlib:
      repo: git://github.com/Yelp/puppetlabs-stdlib.git
    apt:
      repo: git://github.com/puppetlabs/puppetlabs-apt.git
      ref: 2.1.0
  symlinks:
    docker: "#{source_dir}"
